services:
  hono-postgres:
    image: postgres:16.6-alpine3.21
    container_name: hono-postgres
    labels:
      - dev.orbstack.domains=postgres.hono.local
    environment:
      POSTGRES_DB: hono
      POSTGRES_USER: hono
      POSTGRES_PASSWORD: pgpass
    volumes:
      - hono-postgres-volume:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/0.schema.sql
      - ./seed.sql:/docker-entrypoint-initdb.d/1.seed.sql
      # - ./seed.dev.sql:/docker-entrypoint-initdb.d/2.seed.dev.sql
    networks:
      - hono-network
  hono-postgres-test:
    image: postgres:16.6-alpine3.21
    container_name: hono-postgres-test
    labels:
      - dev.orbstack.domains=test.postgres.hono.local
    environment:
      POSTGRES_DB: hono
      POSTGRES_USER: hono
      POSTGRES_PASSWORD: pgpass
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/0.schema.sql
      - ./seed.sql:/docker-entrypoint-initdb.d/1.seed.sql
    networks:
      - hono-network
networks:
  hono-network:
    name: hono-network
volumes:
  hono-postgres-volume:
